global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  external_labels:
      monitor: 'my-project'

rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
         - targets:
           - localhost:9090
           - cadvisor:8080
           - node-exporter:9100

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://pagertree.com
        - https://www.google.com
        - https://prometheus.io
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "blackbox_exporter:9115"  # Blackbox exporter.
      - target_label: region
        replacement: "local"

  - job_name: 'monitor_ping'
    scrape_interval: 5s
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - targets/*.yml
        refresh_interval: 1m
    metrics_path: /probe
    params:
      module: [icmp]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackboc_exporter:9115
