global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"

  - job_name: 'monitor_ping'
    scrape_interval: 5s
    scrape_timeout: 5s
    file_sd_configs:
      - files:
        - targets/*.yml
        refresh_interval: 1m
    metrics_path: /probe
    params:
      module: [icmp]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
